export const Properties = [
  {
    id: 1,
    address: "0 Sheridan Plaza",
    active: false,
    tenant: 9,
    request: 81,
    area: 246,
  },
  {
    id: 2,
    address: "09 David Park",
    active: true,
    tenant: 6,
    request: 63,
    area: 418,
  },
  {
    id: 3,
    address: "0 Lakewood Gardens Terrace",
    active: false,
    tenant: 1,
    request: 23,
    area: 278,
  },
  {
    id: 4,
    address: "21 Redwing Plaza",
    active: false,
    tenant: 4,
    request: 21,
    area: 459,
  },
  {
    id: 5,
    address: "058 Pierstorff Street",
    active: true,
    tenant: 5,
    request: 45,
    area: 732,
  },
  {
    id: 6,
    address: "80691 Havey Terrace",
    active: false,
    tenant: 7,
    request: 83,
    area: 729,
  },
  {
    id: 7,
    address: "3 Michigan Drive",
    active: false,
    tenant: 1,
    request: 63,
    area: 698,
  },
  {
    id: 8,
    address: "25681 Charing Cross Trail",
    active: false,
    tenant: 10,
    request: 91,
    area: 731,
  },
  {
    id: 9,
    address: "8648 Packers Crossing",
    active: false,
    tenant: 3,
    request: 98,
    area: 595,
  },
  {
    id: 10,
    address: "598 Springview Plaza",
    active: false,
    tenant: 8,
    request: 10,
    area: 352,
  },
  {
    id: 11,
    address: "5 Commercial Drive",
    active: false,
    tenant: 1,
    request: 85,
    area: 110,
  },
  {
    id: 12,
    address: "8 Sutherland Terrace",
    active: false,
    tenant: 3,
    request: 74,
    area: 39,
  },
  {
    id: 13,
    address: "99796 Village Green Terrace",
    active: false,
    tenant: 1,
    request: 86,
    area: 475,
  },
  {
    id: 14,
    address: "949 Scoville Park",
    active: true,
    tenant: 1,
    request: 32,
    area: 77,
  },
  {
    id: 15,
    address: "4862 Melvin Center",
    active: false,
    tenant: 3,
    request: 16,
    area: 583,
  },
  {
    id: 16,
    address: "391 Milwaukee Lane",
    active: false,
    tenant: 4,
    request: 84,
    area: 290,
  },
  {
    id: 17,
    address: "94523 Comanche Alley",
    active: true,
    tenant: 2,
    request: 62,
    area: 621,
  },
  {
    id: 18,
    address: "31 Farragut Court",
    active: false,
    tenant: 7,
    request: 39,
    area: 485,
  },
  {
    id: 19,
    address: "7472 Beilfuss Point",
    active: true,
    tenant: 10,
    request: 77,
    area: 443,
  },
  {
    id: 20,
    address: "59925 La Follette Park",
    active: false,
    tenant: 6,
    request: 39,
    area: 93,
  },
  {
    id: 21,
    address: "960 Old Shore Crossing",
    active: true,
    tenant: 5,
    request: 63,
    area: 782,
  },
  {
    id: 22,
    address: "19102 Pleasure Center",
    active: false,
    tenant: 6,
    request: 88,
    area: 181,
  },
  {
    id: 23,
    address: "7745 Cottonwood Parkway",
    active: true,
    tenant: 9,
    request: 93,
    area: 735,
  },
  {
    id: 24,
    address: "5 Northridge Center",
    active: true,
    tenant: 9,
    request: 46,
    area: 976,
  },
  {
    id: 25,
    address: "4 Ludington Court",
    active: false,
    tenant: 5,
    request: 27,
    area: 767,
  },
  {
    id: 26,
    address: "73 Kropf Point",
    active: true,
    tenant: 2,
    request: 41,
    area: 578,
  },
  {
    id: 27,
    address: "2 Troy Circle",
    active: true,
    tenant: 6,
    request: 21,
    area: 869,
  },
  {
    id: 28,
    address: "41 Buell Center",
    active: false,
    tenant: 1,
    request: 32,
    area: 982,
  },
  {
    id: 29,
    address: "84 Little Fleur Pass",
    active: false,
    tenant: 2,
    request: 99,
    area: 146,
  },
  {
    id: 30,
    address: "7 Chive Avenue",
    active: false,
    tenant: 2,
    request: 95,
    area: 633,
  },
  {
    id: 31,
    address: "502 Mayfield Street",
    active: true,
    tenant: 2,
    request: 50,
    area: 586,
  },
  {
    id: 32,
    address: "9129 Prentice Hill",
    active: true,
    tenant: 8,
    request: 34,
    area: 24,
  },
  {
    id: 33,
    address: "18 Veith Trail",
    active: false,
    tenant: 6,
    request: 7,
    area: 768,
  },
  {
    id: 34,
    address: "4329 5th Street",
    active: true,
    tenant: 9,
    request: 96,
    area: 776,
  },
  {
    id: 35,
    address: "58 Nova Drive",
    active: false,
    tenant: 1,
    request: 58,
    area: 956,
  },
  {
    id: 36,
    address: "9 Schlimgen Court",
    active: true,
    tenant: 1,
    request: 69,
    area: 823,
  },
  {
    id: 37,
    address: "9 Lakewood Gardens Center",
    active: false,
    tenant: 5,
    request: 27,
    area: 911,
  },
  {
    id: 38,
    address: "1 Arapahoe Place",
    active: false,
    tenant: 5,
    request: 25,
    area: 563,
  },
  {
    id: 39,
    address: "65907 Quincy Plaza",
    active: false,
    tenant: 9,
    request: 67,
    area: 51,
  },
  {
    id: 40,
    address: "907 Farwell Lane",
    active: true,
    tenant: 7,
    request: 86,
    area: 363,
  },
  {
    id: 41,
    address: "42139 Carioca Crossing",
    active: false,
    tenant: 8,
    request: 12,
    area: 892,
  },
  {
    id: 42,
    address: "23816 Mesta Junction",
    active: true,
    tenant: 4,
    request: 54,
    area: 126,
  },
  {
    id: 43,
    address: "337 Schurz Center",
    active: false,
    tenant: 4,
    request: 89,
    area: 191,
  },
  {
    id: 44,
    address: "7 Mccormick Parkway",
    active: false,
    tenant: 3,
    request: 52,
    area: 379,
  },
  {
    id: 45,
    address: "63884 Transport Avenue",
    active: true,
    tenant: 10,
    request: 87,
    area: 63,
  },
  {
    id: 46,
    address: "95189 Park Meadow Court",
    active: true,
    tenant: 3,
    request: 42,
    area: 683,
  },
  {
    id: 47,
    address: "3 Kingsford Trail",
    active: false,
    tenant: 8,
    request: 74,
    area: 219,
  },
  {
    id: 48,
    address: "11527 Sauthoff Junction",
    active: false,
    tenant: 5,
    request: 64,
    area: 279,
  },
  {
    id: 49,
    address: "74799 Esker Crossing",
    active: false,
    tenant: 1,
    request: 7,
    area: 821,
  },
  {
    id: 50,
    address: "3336 Lerdahl Terrace",
    active: false,
    tenant: 1,
    request: 19,
    area: 63,
  },
  {
    id: 51,
    address: "6653 Thackeray Point",
    active: true,
    tenant: 9,
    request: 91,
    area: 828,
  },
  {
    id: 52,
    address: "52178 Northwestern Parkway",
    active: true,
    tenant: 2,
    request: 47,
    area: 865,
  },
  {
    id: 53,
    address: "4 Starling Lane",
    active: false,
    tenant: 1,
    request: 20,
    area: 757,
  },
  {
    id: 54,
    address: "752 Surrey Circle",
    active: true,
    tenant: 6,
    request: 81,
    area: 862,
  },
  {
    id: 55,
    address: "5 Northland Park",
    active: true,
    tenant: 2,
    request: 88,
    area: 613,
  },
  {
    id: 56,
    address: "93441 Westridge Pass",
    active: true,
    tenant: 10,
    request: 71,
    area: 631,
  },
  {
    id: 57,
    address: "370 Meadow Valley Park",
    active: true,
    tenant: 8,
    request: 79,
    area: 647,
  },
  {
    id: 58,
    address: "2 Jackson Point",
    active: false,
    tenant: 10,
    request: 30,
    area: 596,
  },
  {
    id: 59,
    address: "4251 Gale Trail",
    active: false,
    tenant: 4,
    request: 46,
    area: 110,
  },
  {
    id: 60,
    address: "15 Farragut Alley",
    active: true,
    tenant: 10,
    request: 79,
    area: 303,
  },
  {
    id: 61,
    address: "900 Novick Alley",
    active: true,
    tenant: 10,
    request: 61,
    area: 136,
  },
  {
    id: 62,
    address: "50545 Derek Crossing",
    active: true,
    tenant: 5,
    request: 61,
    area: 902,
  },
  {
    id: 63,
    address: "3456 8th Trail",
    active: false,
    tenant: 8,
    request: 49,
    area: 545,
  },
  {
    id: 64,
    address: "79 Toban Hill",
    active: false,
    tenant: 2,
    request: 8,
    area: 89,
  },
  {
    id: 65,
    address: "40092 Macpherson Point",
    active: false,
    tenant: 6,
    request: 73,
    area: 18,
  },
  {
    id: 66,
    address: "72460 Holy Cross Avenue",
    active: true,
    tenant: 8,
    request: 16,
    area: 599,
  },
  {
    id: 67,
    address: "8 Gale Center",
    active: true,
    tenant: 10,
    request: 33,
    area: 444,
  },
  {
    id: 68,
    address: "796 Annamark Court",
    active: false,
    tenant: 4,
    request: 15,
    area: 134,
  },
  {
    id: 69,
    address: "3005 Esker Lane",
    active: true,
    tenant: 6,
    request: 27,
    area: 326,
  },
  {
    id: 70,
    address: "02424 Buell Trail",
    active: false,
    tenant: 2,
    request: 21,
    area: 252,
  },
  {
    id: 71,
    address: "3 Northfield Park",
    active: false,
    tenant: 10,
    request: 69,
    area: 313,
  },
  {
    id: 72,
    address: "48 Graedel Plaza",
    active: true,
    tenant: 2,
    request: 47,
    area: 44,
  },
  {
    id: 73,
    address: "4561 Dryden Lane",
    active: true,
    tenant: 7,
    request: 92,
    area: 966,
  },
  {
    id: 74,
    address: "1055 Hollow Ridge Trail",
    active: false,
    tenant: 8,
    request: 26,
    area: 562,
  },
  {
    id: 75,
    address: "27 Monica Circle",
    active: false,
    tenant: 7,
    request: 66,
    area: 993,
  },
  {
    id: 76,
    address: "3888 Sunnyside Terrace",
    active: true,
    tenant: 5,
    request: 84,
    area: 992,
  },
  {
    id: 77,
    address: "168 Carey Center",
    active: true,
    tenant: 8,
    request: 3,
    area: 307,
  },
  {
    id: 78,
    address: "5 Surrey Place",
    active: false,
    tenant: 2,
    request: 81,
    area: 549,
  },
  {
    id: 79,
    address: "31 Scott Crossing",
    active: false,
    tenant: 6,
    request: 99,
    area: 547,
  },
  {
    id: 80,
    address: "72 5th Point",
    active: false,
    tenant: 8,
    request: 81,
    area: 946,
  },
  {
    id: 81,
    address: "64 Pearson Avenue",
    active: true,
    tenant: 4,
    request: 84,
    area: 681,
  },
  {
    id: 82,
    address: "90791 Doe Crossing Road",
    active: false,
    tenant: 8,
    request: 58,
    area: 702,
  },
  {
    id: 83,
    address: "63 Browning Trail",
    active: true,
    tenant: 1,
    request: 45,
    area: 308,
  },
  {
    id: 84,
    address: "59 Michigan Court",
    active: false,
    tenant: 5,
    request: 71,
    area: 705,
  },
  {
    id: 85,
    address: "81 Toban Trail",
    active: true,
    tenant: 6,
    request: 50,
    area: 82,
  },
  {
    id: 86,
    address: "81 Elgar Park",
    active: false,
    tenant: 4,
    request: 89,
    area: 385,
  },
  {
    id: 87,
    address: "2 Tennyson Point",
    active: true,
    tenant: 10,
    request: 56,
    area: 777,
  },
  {
    id: 88,
    address: "4361 Clemons Junction",
    active: true,
    tenant: 7,
    request: 75,
    area: 294,
  },
  {
    id: 89,
    address: "7 Manley Circle",
    active: true,
    tenant: 9,
    request: 68,
    area: 255,
  },
  {
    id: 90,
    address: "5 Fallview Pass",
    active: false,
    tenant: 2,
    request: 29,
    area: 292,
  },
  {
    id: 91,
    address: "990 Quincy Crossing",
    active: false,
    tenant: 9,
    request: 37,
    area: 719,
  },
  {
    id: 92,
    address: "94556 Aberg Street",
    active: false,
    tenant: 10,
    request: 89,
    area: 410,
  },
  {
    id: 93,
    address: "0422 Messerschmidt Place",
    active: true,
    tenant: 6,
    request: 28,
    area: 820,
  },
  {
    id: 94,
    address: "2702 Glendale Hill",
    active: false,
    tenant: 3,
    request: 95,
    area: 645,
  },
  {
    id: 95,
    address: "01433 Becker Hill",
    active: true,
    tenant: 10,
    request: 57,
    area: 87,
  },
  {
    id: 96,
    address: "817 Havey Park",
    active: false,
    tenant: 10,
    request: 18,
    area: 14,
  },
  {
    id: 97,
    address: "743 Moland Way",
    active: true,
    tenant: 1,
    request: 27,
    area: 808,
  },
  {
    id: 98,
    address: "06554 Scofield Way",
    active: false,
    tenant: 6,
    request: 96,
    area: 314,
  },
  {
    id: 99,
    address: "713 Colorado Road",
    active: true,
    tenant: 4,
    request: 86,
    area: 79,
  },
  {
    id: 100,
    address: "121 Oneill Point",
    active: false,
    tenant: 2,
    request: 6,
    area: 166,
  },
  {
    id: 101,
    address: "842 Butternut Terrace",
    active: false,
    tenant: 1,
    request: 36,
    area: 643,
  },
  {
    id: 102,
    address: "3792 Northport Plaza",
    active: false,
    tenant: 7,
    request: 24,
    area: 689,
  },
  {
    id: 103,
    address: "31281 Leroy Terrace",
    active: true,
    tenant: 5,
    request: 51,
    area: 333,
  },
  {
    id: 104,
    address: "568 Sachs Parkway",
    active: true,
    tenant: 5,
    request: 75,
    area: 830,
  },
  {
    id: 105,
    address: "95875 Melvin Alley",
    active: true,
    tenant: 7,
    request: 6,
    area: 169,
  },
  {
    id: 106,
    address: "82 Oneill Center",
    active: false,
    tenant: 8,
    request: 79,
    area: 27,
  },
  {
    id: 107,
    address: "074 Sunnyside Avenue",
    active: false,
    tenant: 1,
    request: 10,
    area: 661,
  },
  {
    id: 108,
    address: "63845 Porter Circle",
    active: false,
    tenant: 8,
    request: 43,
    area: 581,
  },
  {
    id: 109,
    address: "2826 Morningstar Plaza",
    active: true,
    tenant: 6,
    request: 94,
    area: 982,
  },
  {
    id: 110,
    address: "68444 Atwood Court",
    active: true,
    tenant: 10,
    request: 82,
    area: 366,
  },
  {
    id: 111,
    address: "030 Brown Lane",
    active: false,
    tenant: 8,
    request: 83,
    area: 680,
  },
  {
    id: 112,
    address: "278 Moulton Terrace",
    active: false,
    tenant: 5,
    request: 7,
    area: 274,
  },
  {
    id: 113,
    address: "76 Nancy Center",
    active: false,
    tenant: 5,
    request: 87,
    area: 354,
  },
  {
    id: 114,
    address: "5216 Anniversary Lane",
    active: true,
    tenant: 4,
    request: 18,
    area: 863,
  },
  {
    id: 115,
    address: "932 Pepper Wood Terrace",
    active: true,
    tenant: 8,
    request: 43,
    area: 71,
  },
  {
    id: 116,
    address: "0 Anzinger Court",
    active: true,
    tenant: 3,
    request: 37,
    area: 452,
  },
  {
    id: 117,
    address: "56318 Victoria Drive",
    active: false,
    tenant: 1,
    request: 68,
    area: 531,
  },
  {
    id: 118,
    address: "634 Ilene Plaza",
    active: false,
    tenant: 4,
    request: 82,
    area: 425,
  },
];
